# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jend < Formula
  desc "JEND: Just Enough Network Drop - Modern, secure, P2P file transfer."
  homepage "https://github.com/darkprince558/jend"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darkprince558/JEND/releases/download/v2.4.0/jend_Darwin_x86_64.tar.gz"
      sha256 "f6eb9569d40009acdb60a28383eec8d8167b157ea0a056a4f1a2bbb3408d4916"

      define_method(:install) do
        bin.install "jend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darkprince558/JEND/releases/download/v2.4.0/jend_Darwin_arm64.tar.gz"
      sha256 "8766bffbf108c61abef5c3686b7d7896f333d161679c38eb56c97b68ddbb180d"

      define_method(:install) do
        bin.install "jend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darkprince558/JEND/releases/download/v2.4.0/jend_Linux_x86_64.tar.gz"
      sha256 "11e202f8370be64b3799c0d377d136c54330d1d9363257c370c025bc0a924cbe"
      define_method(:install) do
        bin.install "jend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darkprince558/JEND/releases/download/v2.4.0/jend_Linux_arm64.tar.gz"
      sha256 "3b1bb92277337db63875bda8a2eca76d13a0c72129f2108dc9cd4628667a93ba"
      define_method(:install) do
        bin.install "jend"
      end
    end
  end
end
